import type { Metadata } from "next";
import { Epilogue, Manrope, IBM_Plex_Sans_Arabic } from "next/font/google";
import { ThemeProvider } from "@/theme";

import Header from "@/components/layout/header/Header";

import "./globals.css";

/* ------  Fonts  ------ */
const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-epilogue",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],

  variable: "--font-manrope",
});

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans-arabic",
});

/* ------  Metadata  ------ */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${epilogue.variable} ${manrope.variable} ${ibmPlexSansArabic.variable}`}
    >
      <body>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
